/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HealthRouteImport } from './routes/health'
import { Route as MemberRouteImport } from './routes/member'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as TestsRouteImport } from './routes/tests'
import { Route as AuthLineCallbackRouteImport } from './routes/auth.line.callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberRoute = MemberRouteImport.update({
  id: '/member',
  path: '/member',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const TestsRoute = TestsRouteImport.update({
  id: '/tests',
  path: '/tests',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLineCallbackRoute = AuthLineCallbackRouteImport.update({
  id: '/auth/line/callback',
  path: '/auth/line/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/member': typeof MemberRoute
  '/reports': typeof ReportsRoute
  '/shop': typeof ShopRoute
  '/tests': typeof TestsRoute
  '/auth/line/callback': typeof AuthLineCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/member': typeof MemberRoute
  '/reports': typeof ReportsRoute
  '/shop': typeof ShopRoute
  '/tests': typeof TestsRoute
  '/auth/line/callback': typeof AuthLineCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/member': typeof MemberRoute
  '/reports': typeof ReportsRoute
  '/shop': typeof ShopRoute
  '/tests': typeof TestsRoute
  '/auth/line/callback': typeof AuthLineCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/health'
    | '/member'
    | '/reports'
    | '/shop'
    | '/tests'
    | '/auth/line/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/health'
    | '/member'
    | '/reports'
    | '/shop'
    | '/tests'
    | '/auth/line/callback'
  id:
    | '__root__'
    | '/'
    | '/health'
    | '/member'
    | '/reports'
    | '/shop'
    | '/tests'
    | '/auth/line/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HealthRoute: typeof HealthRoute
  MemberRoute: typeof MemberRoute
  ReportsRoute: typeof ReportsRoute
  ShopRoute: typeof ShopRoute
  TestsRoute: typeof TestsRoute
  AuthLineCallbackRoute: typeof AuthLineCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/member': {
      id: '/member'
      path: '/member'
      fullPath: '/member'
      preLoaderRoute: typeof MemberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tests': {
      id: '/tests'
      path: '/tests'
      fullPath: '/tests'
      preLoaderRoute: typeof TestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/line/callback': {
      id: '/auth/line/callback'
      path: '/auth/line/callback'
      fullPath: '/auth/line/callback'
      preLoaderRoute: typeof AuthLineCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HealthRoute: HealthRoute,
  MemberRoute: MemberRoute,
  ReportsRoute: ReportsRoute,
  ShopRoute: ShopRoute,
  TestsRoute: TestsRoute,
  AuthLineCallbackRoute: AuthLineCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
